# Generated by Django 4.0 on 2022-05-14 11:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pancard', models.BooleanField(default=False)),
                ('aadharcard', models.BooleanField(default=False)),
                ('passpord', models.BooleanField(default=False)),
                ('driving_license', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('pancard', models.ImageField(blank=True, default='userFiles/default.png', null=True, upload_to=users.models.UserInfo.get_image_path)),
                ('aadharcard', models.ImageField(blank=True, default='userFiles/default.png', null=True, upload_to=users.models.UserInfo.get_image_path)),
                ('passport', models.ImageField(blank=True, default='userFiles/default.png', null=True, upload_to=users.models.UserInfo.get_image_path)),
                ('driving_license', models.ImageField(blank=True, default='userFiles/default.png', null=True, upload_to=users.models.UserInfo.get_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '91723456784'. Up to 12 digits allowed.", regex='^(0|91)?[7-9][0-9]{9}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.roleassigned')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
