# Generated by Django 4.0 on 2022-05-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleassigned',
            name='driving_license',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='driving_license',
        ),
    ]
