# Generated by Django 4.0 on 2022-05-11 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='auto_increment_id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.AutoField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phone',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '91723456784'. Up to 12 digits allowed.", regex='^(0|91)?[7-9][0-9]{9}$')]),
        ),
    ]
