# Generated by Django 4.0 on 2022-05-14 12:39

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_roleassigned_driving_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='driving_license',
            field=models.ImageField(blank=True, default='userFiles/default.png', null=True, upload_to=users.models.UserInfo.get_image_path),
        ),
    ]
