# Generated by Django 4.0.3 on 2022-05-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userdata_tc'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassigned',
            name='driving_license',
            field=models.BooleanField(default=False),
        ),
    ]
