# Generated by Django 4.0 on 2022-05-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userdata_tc'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pancard', models.ImageField(upload_to='')),
                ('aadharcard', models.ImageField(upload_to='')),
                ('passport', models.ImageField(upload_to='')),
            ],
        ),
    ]
