# Generated by Django 3.1 on 2022-05-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220506_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='aadharcard',
            field=models.ImageField(blank=True, default='userFiles/default.png', null=True, upload_to='userFiles'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pancard',
            field=models.ImageField(blank=True, default='userFiles/default.png', null=True, upload_to='userFiles'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='passport',
            field=models.ImageField(blank=True, default='userFiles/default.png', null=True, upload_to='userFiles'),
        ),
    ]
