# Generated by Django 4.0 on 2022-05-14 16:26

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userdata_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='aadharcard',
            field=users.models.CustomImageField(blank=True, default='userFiles/default.png', null=True, upload_to='tmp'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='driving_license',
            field=users.models.CustomImageField(blank=True, default='userFiles/default.png', null=True, upload_to='tmp'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pancard',
            field=users.models.CustomImageField(blank=True, default='userFiles/default.png', null=True, upload_to='tmp'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='passport',
            field=users.models.CustomImageField(blank=True, default='userFiles/default.png', null=True, upload_to='tmp'),
        ),
    ]
